version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: inscrebed-sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rbmf2022
      MYSQL_DATABASE: inscrebedDB
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE